server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.253.128
    password: 123456
  rabbitmq:
    virtual-host: /chengge
    port: 5672
    username: chengge
    host: 192.168.253.128
    password: chengge

gmall:
  jwt:
    pubKeyPath: E:\ideaProject\easyMall\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    #订单肯定会登录了

alipay:
  app_id: 2016102100732801
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCU+b+AsKZk3A1JvPE401ZLdFTgem0/v71Mxju7CE8tsBMm4o7qyJT473fBZ1ajynQ2a3VnU8DYsZLlWU/J6o2S4DEL5EDL2otUyTsZ2HZogMr5DbU8TVmy/Vo541u8V3D8AXcCikhw978qaxOK6zet6XY+kLRy54gdzM7HSzkwPG8eniSOkvUrgVP755i6wNq/gBUl2uXmLIVda4WhG3UDuZSom4WCAuv24oet9yq1EqwW18qsQmXwYoWllHRSgkNQWoz7g5/xgkQ5Wq21gFtp62SJFENn/d4qcfkAtkDZPRN2985ShtH0I2Fqk+yWeSxBGuQNtowpb/qyNHU9WHWzAgMBAAECggEBAIAQBRhKQm93XpDhs/cmbQsl8ISbmWhwmfjye4w3A2GB96S4oySe0rj/mdGO1MKuGaJiU6VEMQXV+DHhyZ4IXDVDNcZEK5NRxe5Xoc+A7aC9/j2EFCTHVXFxKuuST1yjSkPHupdbahR6VEHRlBYaR13f0D7OQ+B2ueLsGWDmgD2+lfIABwl3oZbsIsftgbfNkcwMGsAWhteVgfrzCoU7CANEOz5B8nZxbNIYHcxz4FENiUo8JIhksmgIJ53wr57fTMtcFOj/IuqOJhxzfYNzfFz+Zg+H3ajW5GQMUPjHvgNTm3cpV2xwbJOh52nuoheWGCaG2zDcTxE2jvFGRsuzy5kCgYEAxxnFn+dLnW7tjWkmSNVWYvocqoZfQcEbWbHeTILksZVspC64CoWcQyEnAccEU4fJ7d6BJBRAOkdSzpsK/eIHQG4l9YbrmP8fMd46QFZ5FAaZcXbZ9+/cookmjvTDEf1ibIpiIFq5+AI1SKZ1CpBLm3SNNbfwVYGUZtef8o5HqrcCgYEAv4zRiKQRSTq6Dm7frWFSmFXvolnKA2gMwEzqnrxyCjQfHVCeTXT+DbO75WqKy7QSR9kGPV5aI+6g9YkWmpbtqPUvxzj1BIRjWbRVV95uTsUZzErVbKR0cEcvzxDU4lA7/eYiCgE8AjW8FG6Jg6Wm2AZTrn2nyWG7CDlYkbTpQOUCgYAFD7CoafbQH7vGNoAUpee2SGlmJFhTkZciZpUiGMm7gfLrEYz4J4Fba4JUVzzS6sbFVzytMB6Z3KpMOkDDR3Wru6EXZsCieQnP+Lg+XnRhf/FyovTTirNvJlFmnO5AjNJts+7ep6/GkDfOivy6sgRaBVJ5pR1k7xBYtO6J+ff0bQKBgDWYUBRcW53SubZKHXmkjnijKt6RIu3bEh5IJyls7reeJ8qLARAJGQB6dqtVKSqf4rGJrq5DFROStCSfS9zLOAobOFgUvrGZ3TZ/N5XTXafajEJV+ethBFdaA617NyVvb6m113ZXLBQuNsa8uutD0TAGbSmYbPbyymMdsINsTAtlAoGBALDPrgHabPH6IWEjYu4DQHGu28+0Y5Kwy3ywRjpu25BHEwhNgNG4yoZ6YwID2gsP4mGCWRz+iDqdYJmD2TCP47Rd5wWtJe2Exh5AHqYfFEoKSDiTUxy8f/gZlApjGsWoHT0Sif3ZNRwN0CSYTXo1vLtPAtHsOaYTGb47bp+slPnA
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqjdsSk8PF5L40oOjL+a4za2WrrUN5+BpFbRxgut1Z/P/4UNrBikJdyvtrlzR6fK8nwmVyCHE240WTuZItUkcPfShxyuFjvGEFshVK0H5eLevnuFJfctyFFHZQ87VzE2Qehjww5cblASOyIFYzJE2JQQyI1UA6YKoX+zJIXlFL25H5A0LNGJRCSOOOcVuGq3XFSL8nZHV19O8ukvYr7Elt0OZDE571RyXYvVYzSEO7ixhxfTUR4WKU/4NjA2Dqkh3KjEqhih6wFLboZNe2dAY2n0z97p4SBP0WXwPDJ71k52mvNBSB04oACnDRqs+9Er9jg5lTGCrqiSYhVYPu8XVoQIDAQAB
  notify_url: http://jv8dgp2vs3.52http.tech/api/order/pay/success
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do



ribbon:
  ReadTimeout: 60000 #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接的超时时间



