server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
gmall:
  jwt:
    pubKeyPath: E:\ideaProject\easyMall\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\ideaProject\easyMall\\rsa\\rsa.pri # 私钥地址
    secret: sf3423jsdf#3$@FDS32 #加盐
    expire: 180 # 过期时间,单位分钟
    cookieName: GMALL_TOKEN
ribbon:
  ReadTimeout: 60000 #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接的超时时间